### ISSUE TITLE
Login/Register Issue

### ISSUE THREAD

**Issue by mahekn23** [Auto-DL/Auto-DL#190]
## Bug Report

No action after clicking the login/register button

### Current Behavior
getting an error msg in the backend cmd
![Screenshot (69)](https://user-images.githubusercontent.com/66668119/123420410-275da480-d5d9-11eb-98b6-2dd29e87231a.png)
![Screenshot (70)](https://user-images.githubusercontent.com/66668119/123420415-288ed180-d5d9-11eb-8d01-3bb1fdcd1ab5.png)

ERROR LOG

MongoDB connected
Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "D:\Auto-DL\BackEndApp\authv1\views.py", line 17, in login
    user = user.find()
  File "D:\Auto-DL\BackEndApp\authv1\models.py", line 57, in find
    return self.collection.find_one({
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\pymongo\collection.py", line 1319, in find_one
    for result in cursor.limit(-1):
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\pymongo\cursor.py", line 1207, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\pymongo\cursor.py", line 1100, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\pymongo\mongo_client.py", line 1816, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\pymongo\mongo_client.py", line 1766, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\pymongo\mongo_client.py", line 1802, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\pymongo\topology.py", line 490, in get_server_session
    self._select_servers_loop(
  File "C:\Users\Mahek Nagdev\AppData\Local\Programs\Python\Python38\lib\site-packages\pymongo\topology.py", line 215, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: kuro-shard-00-01.9glt4.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125),kuro-shard-00-02.9glt4.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125),kuro-shard-00-00.9glt4.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125), Timeout: 30s, Topology Description: <TopologyDescription id: 60d5c03b070cb3952b7ee8ff, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('kuro-shard-00-00.9glt4.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('kuro-shard-00-00.9glt4.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')>, <ServerDescription ('kuro-shard-00-01.9glt4.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('kuro-shard-00-01.9glt4.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')>, <ServerDescription ('kuro-shard-00-02.9glt4.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('kuro-shard-00-02.9glt4.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')>]>
[25/Jun/2021 17:09:06] "POST /auth/login/ HTTP/1.1" 500 142625

**Comment by ADI10HERO** [comment]
Thank you for raising this @mahekn23, can you please copy and paste the error log in textual format too (so it's easier for others to  have a look/copy-paste)
