### ISSUE TITLE
Logging on windows gives arbitrary error

### ISSUE THREAD

**Issue by ADI10HERO** [Auto-DL/Auto-DL#312]
## Bug Report

Logging fails on windows.

### Current Behavior
```sh
2021-09-01 21:11:09 | django.server/log_message | INFO: "POST /v1/hyperparams/get/ HTTP/1.1" 200 213
--- Logging error ---
Traceback (most recent call last):
  File "D:\Softwares\Anaconda\envs\autodl\lib\logging\handlers.py", line 70, in emit
    self.doRollover()
  File "D:\Softwares\Anaconda\envs\autodl\lib\logging\handlers.py", line 394, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "D:\Softwares\Anaconda\envs\autodl\lib\logging\handlers.py", line 111, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\ADI\\AutoDL\\code\\Auto-DL\\BackEndApp\\logs\\app.log' -> 'D:\\ADI\\AutoDL\\code\\Auto-DL\\BackEndApp\\logs\\app.log.2021-08-01'
Call stack:
  File "D:\Softwares\Anaconda\envs\autodl\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "D:\Softwares\Anaconda\envs\autodl\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\Softwares\Anaconda\envs\autodl\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Softwares\Anaconda\envs\autodl\lib\socketserver.py", line 650, in process_request_thread     
    self.finish_request(request, client_address)
  File "D:\Softwares\Anaconda\envs\autodl\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\Softwares\Anaconda\envs\autodl\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\Softwares\Anaconda\envs\autodl\lib\site-packages\django\core\servers\basehttp.py", line 176, 
in handle
    self.handle_one_request()
  File "D:\Softwares\Anaconda\envs\autodl\lib\site-packages\django\core\servers\basehttp.py", line 201, 
in handle_one_request
    handler.run(self.server.get_app())
  File "D:\Softwares\Anaconda\envs\autodl\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "D:\Softwares\Anaconda\envs\autodl\lib\wsgiref\handlers.py", line 196, in finish_response        
    self.close()
  File "D:\Softwares\Anaconda\envs\autodl\lib\site-packages\django\core\servers\basehttp.py", line 118, 
in close
    super().close()
  File "D:\Softwares\Anaconda\envs\autodl\lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
  File "D:\Softwares\Anaconda\envs\autodl\lib\http\server.py", line 544, in log_request
    self.requestline, str(code), str(size))
  File "D:\Softwares\Anaconda\envs\autodl\lib\site-packages\django\core\servers\basehttp.py", line 161, 
in log_message
    level(format, *args, extra=extra)
Message: '"%s" %s %s'
```

### Expected behavior/code
No such logs or errors?

### ⚙️ Environment

- `Python` version(s):
    *good*: 3.8
- `OS`: Windows 10

**Comment by gagandeepp** [comment]
@RusherRG  asign this to me

**Comment by gagandeepp** [comment]
Not interested ,I am unable to login to application need to make changes manually to setup the application

Mongodb uri you guys provided has query string which is not allowing the backend to start and you guys need to fix the CORS issues

**Comment by McTechie** [comment]
Heyy @inomag if you're interested to take up this issue, I'd assign this to you
