### ISSUE TITLE
UnboundLocalError: local variable 'username' referenced before assignment

### ISSUE THREAD

**Issue by RusherRG** [Auto-DL/Auto-DL#315]
### Current Behavior

```
 2021-09-03 13:02:30 | django.request/log_response | ERROR: Internal Server Error: /auth/register/
Traceback (most recent call last):
  File "/home/rusherrg/Projects/AutoDL/Auto-DL/BackEndApp/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/rusherrg/Projects/AutoDL/Auto-DL/BackEndApp/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rusherrg/Projects/AutoDL/Auto-DL/BackEndApp/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rusherrg/Projects/AutoDL/Auto-DL/BackEndApp/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rusherrg/Projects/AutoDL/Auto-DL/BackEndApp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rusherrg/Projects/AutoDL/Auto-DL/BackEndApp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rusherrg/Projects/AutoDL/Auto-DL/BackEndApp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rusherrg/Projects/AutoDL/Auto-DL/BackEndApp/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rusherrg/Projects/AutoDL/Auto-DL/BackEndApp/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/rusherrg/Projects/AutoDL/Auto-DL/BackEndApp/authv1/views.py", line 75, in register
    {"message": message, "username": username, "token": token}, status=status
UnboundLocalError: local variable 'username' referenced before assignment
```

This error might be triggered for some more API endpoints if the `request` or the `request.data` is malformed since the variable `username` is initialized inside the try-except while the return statement is outside. 

### ⚙️ Environment

- `Python` version(s): 3.8.5
- `OS`: Ubuntu 20.04

### Possible Solution

Just move the return statement inside the try block (same scope). Or just remove the username from the return JSON as there is no need to return it.

**Comment by mharyam** [comment]
Hello @RusherRG 

Can I work on this?

**Comment by RusherRG** [comment]
Yeah sure. Go ahead

**Comment by mharyam** [comment]
Thank you 😂

This is the pull request link: https://github.com/Auto-DL/Auto-DL/pull/319
