### ISSUE TITLE
Docker Backend Not running 

### ISSUE THREAD

**Issue by codewith-arijit** [Auto-DL/Auto-DL#354]
### Current Behavior

The Backend App is not running after installing through Docker. 
I checked through the docker logs, which are as follows:

```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>`
```

### ⚙️ Environment

- `Python` version(s):
    - 3.8.10
- `OS`: Ubuntu 20.04 LTS

**Comment by RusherRG** [comment]
@codewith-arijit  Are you building the docker image using `BackEndApp/Dockerfile`?

**Comment by codewith-arijit** [comment]
> @codewith-arijit Are you building the docker image using `BackEndApp/Dockerfile`? Also, there should be more errors above the snippet you added. Could you please share those as well?

I am using docker-compose, as mentioned in the installation.
Here you go with the whole logs: [Pastebin](https://pastebin.com/raw/heQMrYDJ)
